// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6sio-C9WP-GzRopULuWuEgrzO9O9ATQ',
    appId: '1:1049824199403:web:14cf6ff544dcdbafc0f4ae',
    messagingSenderId: '1049824199403',
    projectId: 'calculator2025-9133c',
    authDomain: 'calculator2025-9133c.firebaseapp.com',
    storageBucket: 'calculator2025-9133c.firebasestorage.app',
    measurementId: 'G-XP3EBVXGSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIaVVtU5NtABn5yjnnhW1mUVKzvQ1vNE',
    appId: '1:1049824199403:android:fdc78cb60b66826cc0f4ae',
    messagingSenderId: '1049824199403',
    projectId: 'calculator2025-9133c',
    storageBucket: 'calculator2025-9133c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOacpsR_KIe5KI2dBkKgO4ELQ9oYz6MU4',
    appId: '1:1049824199403:ios:596574fc3cbbc8afc0f4ae',
    messagingSenderId: '1049824199403',
    projectId: 'calculator2025-9133c',
    storageBucket: 'calculator2025-9133c.firebasestorage.app',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOacpsR_KIe5KI2dBkKgO4ELQ9oYz6MU4',
    appId: '1:1049824199403:ios:596574fc3cbbc8afc0f4ae',
    messagingSenderId: '1049824199403',
    projectId: 'calculator2025-9133c',
    storageBucket: 'calculator2025-9133c.firebasestorage.app',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF6sio-C9WP-GzRopULuWuEgrzO9O9ATQ',
    appId: '1:1049824199403:web:6fe7e8fa43e61e07c0f4ae',
    messagingSenderId: '1049824199403',
    projectId: 'calculator2025-9133c',
    authDomain: 'calculator2025-9133c.firebaseapp.com',
    storageBucket: 'calculator2025-9133c.firebasestorage.app',
    measurementId: 'G-WZZZJCJWQE',
  );
}
